name: Create and merge pull request

on:
  push:
    branches:
      - main
    # paths:
    #   - worker/**


jobs:
  create-branch:
    runs-on: ubuntu-latest 
    name: Create new branch
    outputs: 
      branch_name: ${{ steps.create-branch.outputs.branch_name }}

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0      
      - name: create branch
        id: create-branch
        run: |
            BRANCH_NAME=branch-$GITHUB_RUN_ID
            echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
            git checkout -b $BRANCH_NAME
            git push origin $BRANCH_NAME


  add-files:
    runs-on: ubuntu-latest
    name: Add files to the branch
    needs: create-branch
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0      
      - name: add file to branch and push
        env:
          BRANCH_NAME: ${{ needs.create-branch.outputs.branch_name }}
        run: |
          echo $BRANCH_NAME
          git config --global user.name "CI bot"
          git config --global user.email "cibot@kayjohansen.org"

          git checkout -b $BRANCH_NAME
          touch $BRANCH_NAME.txt
          git add .
          git commit -a -m "add test file $BRANCH_NAME.txt"
          git push -u origin $BRANCH_NAME

  merge-pr:
    runs-on: ubuntu-latest
    name: Create PR and merge
    needs: [create-branch, add-files]

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: create PR
        env:
          BRANCH_NAME: ${{ needs.create-branch.outputs.branch_name }}
        run: |
          echo $BRANCH_NAME