name: Create and merge pull request

on:
  push:
    branches:
      - main
    # paths:
    #   - worker/**


jobs:
  build:
    runs-on: ubuntu-latest 
    name: Create pull request
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: make change and add to pull request
        uses: tj-actions/changed-files@v34
        with:
          since_last_remote_commit: "true"
          files: |
            workers/**          
