name: Create and merge pull request

on:
  push:
    branches:
      - main
    # paths:
    #   - worker/**


jobs:
  branch-name:
    runs-on: ubuntu-latest 
    name: Define branch name and make sure it does not exist
    outputs: 
      branch_name: ${{ steps.define-branch-name.output.branch_name }}

    steps:
      - name: define branch name
        id: define-branch-name
        run: |
            echo 'branch_name=branch-$GITHUB_RUN_ID' >> $GITHUB_OUTPUT          

  add-files:
    runs-on: ubuntu-latest
    name: Add files to the branch
    needs: branch-name
    
    steps:
      - name: add files
        env:
          BRANCH_NAME: ${{ needs.branch-name.output.branch_name }}
        run: |
          echo ${BRANCH_NAME}
