name: Create and merge pull request

on:
  push:
    branches:
      - main
    # paths:
    #   - worker/**


jobs:
  branch-name:
    runs-on: ubuntu-latest 
    name: Define branch name and make sure it does not exist
    outputs: 
      branch_name: ${{ steps.define-branch-name.outputs.branch_name }}

    steps:
      - name: define branch name
        id: define-branch-name
        run: |
            BRANCH_NAME=branch-$GITHUB_RUN_ID
            echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT


  add-files:
    runs-on: ubuntu-latest
    name: Add files to the branch
    needs: branch-name
    
    steps:
      - name: add files
        run: |
          echo ${{ needs.branch-name.outputs.branch_name }}          
